#! /bin/sh

### AUTOSTART ###
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xrandr --auto &
sxhkd &
picom --experimental-backend &
$HOME/.config/polybar/launch.sh
nitrogen --restore &
clipmenud &

### CURSOR ###
xsetroot -cursor_name left_ptr 

### MONITORS ###

## Main monitor
##xrandr --output DP-4 --mode 3440x1440 --rate 120
##xrandr --auto

## workspaces ##
bspc monitor DP-4 -d 1 2 3 4 5 6 7 8

### COLORS ###
bspc config normal_border_color		"#b2b3f4"
bspc config focused_border_color	"#5761ee"
bspc config presel_feedback_color	"#b2b3f4"

### BORDERS ###
bspc config border_width	2
bspc config window_gap		20

### RULES ###
bspc rule -a Deadbeef state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a Galculator state=floating
bspc rule -a mpv state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a vlc state=floating
bspc rule -a foobar2000 state=floating

### OTHER SHIT ###
pgrep -x sxhkd > /dev/null || sxhkd &

bspc config split_ratio		0.50

bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config focus_follows_pointer true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
