#!/bin/sh

# Build & install Paru
{ 
sudo ../.pkgs/paru/install.sh 
} || { 
echo "=> Paru install failed, aborting!" && exit 
}
&&
# Install packages
{ 
sudo paru -S $(cat ../.pkgs/paru/pkgs | cut -d' ' -f1)
} || { 
echo "=> Packages install failed!" 
}
&&
# Move system files
{ 
sudo ./ln.sh
} || { 
echo "=> Moving sys files failed!"
}
&&
# Move user files
{ 
sudo ../.config/ln.sh
} || { 
echo "=> Moving usr files failed!" 
}
&&
echo "=> Finished!" && exit
