#! /bin/sh
##__/\\\_____________________________________________________________________________________________________        
## _\/\\\_____________________________________________________________________________________________________       
##  _\/\\\_______________________/\\\\\\\\\____________________________________________________________________      
##   _\/\\\_________/\\\\\\\\\\__/\\\/////\\\__/\\____/\\___/\\____/\\\\\__/\\\\\____/\\/\\\\\\\______/\\\\\\\\_     
##    _\/\\\\\\\\\__\/\\\//////__\/\\\\\\\\\\__\/\\\__/\\\\_/\\\__/\\\///\\\\\///\\\_\/\\\/////\\\___/\\\//////__    
##     _\/\\\////\\\_\/\\\\\\\\\\_\/\\\//////___\//\\\/\\\\\/\\\__\/\\\_\//\\\__\/\\\_\/\\\___\///___/\\\_________   
##	_\/\\\__\/\\\_\////////\\\_\/\\\__________\//\\\\\/\\\\\___\/\\\__\/\\\__\/\\\_\/\\\_________\//\\\________  
##       _\/\\\\\\\\\___/\\\\\\\\\\_\/\\\___________\//\\\\//\\\____\/\\\__\/\\\__\/\\\_\/\\\__________\///\\\\\\\\_ 
##        _\/////////___\//////////__\///_____________\///__\///_____\///___\///___\///__\///_____________\////////__
##
### AUTOSTART ###
nitrogen --restore &
sxhkd &
picom --log-file /var/log/picom/picom.log &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/home/kio/.config/polybar/launch.sh &
/usr/bin/wired &
clipmenud &

### CURSOR ###
xsetroot -cursor_name left_ptr 
/usr/bin/fixmouse &

### MONITORS ###

## MAIN ##
xrandr --auto DP-4 --mode 3440x1440 --rate 120

## WORKSPACES ##
bspc monitor DP-4 -d 1 2 3 4 5 6 7 8 9 0

### COLORS ###
bspc config normal_border_color		"#f8f8f2"
bspc config focused_border_color	"#f8f8f2"
bspc config presel_feedback_color	"#bd93f9"

### BORDERS ###
bspc config border_width	0
bspc config window_gap		10

### RULES ###
bspc rule -a Nitrogen state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a vlc state=floating
bspc rule -a foobar2000 state=floating
bspc rule -a foobar2000.exe state=floating
bspc rule -a wine state=floating
bspc rule -a MultiMC state=floating
bspc rule -a multimc state=floating
#bspc rule -a Nemo state=floating
bspc rule -a firewall-config state=floating
bspc rule -a Emacs state=tiled
bspc rule -a Doom Emacs state=tiled
bspc rule -a CoreImage state=floating

### OTHER SHIT ###
pgrep -x sxhkd > /dev/null || sxhkd &

bspc config split_ratio		0.50

## POINTER ACTIONS ##
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config focus_follows_pointer true
bspc config borderless_monocle    true
bspc config gapless_monocle       true
