#! /bin/sh
##__/\\\_____________________________________________________________________________________________________        
## _\/\\\_____________________________________________________________________________________________________       
##  _\/\\\_______________________/\\\\\\\\\____________________________________________________________________      
##   _\/\\\_________/\\\\\\\\\\__/\\\/////\\\__/\\____/\\___/\\____/\\\\\__/\\\\\____/\\/\\\\\\\______/\\\\\\\\_     
##    _\/\\\\\\\\\__\/\\\//////__\/\\\\\\\\\\__\/\\\__/\\\\_/\\\__/\\\///\\\\\///\\\_\/\\\/////\\\___/\\\//////__    
##     _\/\\\////\\\_\/\\\\\\\\\\_\/\\\//////___\//\\\/\\\\\/\\\__\/\\\_\//\\\__\/\\\_\/\\\___\///___/\\\_________   
##	_\/\\\__\/\\\_\////////\\\_\/\\\__________\//\\\\\/\\\\\___\/\\\__\/\\\__\/\\\_\/\\\_________\//\\\________  
##       _\/\\\\\\\\\___/\\\\\\\\\\_\/\\\___________\//\\\\//\\\____\/\\\__\/\\\__\/\\\_\/\\\__________\///\\\\\\\\_ 
##        _\/////////___\//////////__\///_____________\///__\///_____\///___\///___\///__\///_____________\////////__

### VARS ###
gap=8
border=2
panel_height=28
export gap
export border
export panel_height

### AUTOSTART ###
nitrogen --restore &
sxhkd &
picom --experimental-backends --log-file /var/log/picom/picom.log &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/home/kio/.config/polybar/launch.sh &
wired &
clipmenud &
nm-applet &
alacritty &

### CURSOR ###
xsetroot -cursor_name left_ptr 
/usr/bin/fixmouse &

### MONITORS ###
xrandr --output DP-2 --primary --mode 3440x1440 --rate 120
##    --output DP-2 --primary --mode 3440x1440 --rate 120 --pos 0x1080
##  --output DP-2 --mode 1920x1080 --rate 240 --pos 760x0

## WORKSPACES ##
bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9 0
##bspc monitor DP-2 -d 1 2 3

### COLORS ###
bspc config normal_border_color		"#f8f8f2"
bspc config focused_border_color	"#bd93f9"
bspc config presel_feedback_color	"#bd93f9"

### BORDERS ###
bspc config border_width	$border
bspc config window_gap		$gap-$border
#bspc config left_padding        -$(($gap+$border))
#bspc config right_padding       -$(($gap+$border))
#bspc config bottom_padding      -$(($gap+$border))
#bspc config top_padding         -$(($gap+$border))
bspc config left_padding        -$border
bspc config right_padding       -$border
bspc config bottom_padding      -$border
bspc config top_padding         -$border

### RULES ###
bspc rule -a Nitrogen state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a vlc state=floating
bspc rule -a foobar2000 state=floating
bspc rule -a foobar2000.exe state=floating
bspc rule -a wine state=floating
bspc rule -a MultiMC state=floating
bspc rule -a multimc state=floating
bspc rule -a firewall-config state=floating
bspc rule -a Emacs state=tiled
bspc rule -a Doom Emacs state=tiled
bspc rule -a CoreImage state=floating
bspc rule -a join? state=floating
bspc rule -a Zoom state=floating
bspc rule -a Peek state=floating
bspc rule -a peek state=floating
bspc rule -a Alacritty state=pseudo_tiled

### OTHER SHIT ###
pgrep -x sxhkd > /dev/null || sxhkd &

bspc config split_ratio             0.52
bspc config focus_follows_pointer   true
bspc config borderless_monocle      true
bspc config gapless_monocle         false
bspc config paddingless_monocle     false

## POINTER ACTIONS ##
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

## BSPC-SPECIFIC SCRIPTS ###

#/home/kio/.dotfiles/scripts/euclid_balancer & 

