#!/bin/bash

NOTIFY_ICON=/usr/share/icons/Papirus/32x32/apps/system-software-update.svg

get_total_updates() {
    UPDATES=$(~/.config/polybar/scripts/check_updates 2>/dev/null | wc -l);
}

while true; do
    get_total_updates

    # Notify user of any updates
    if hash notify-send &>/dev/null; then
        if (( UPDATES > 50 )); then
            notify-send -u critical -i "$NOTIFY_ICON" \
                "Updates available!" "$UPDATES packages need updating"
        elif (( UPDATES > 25 )); then
            notify-send -u normal -i "$NOTIFY_ICON" \
                "Updates available!" "$UPDATES packages need updating"
        elif (( UPDATES > 10 )); then
            notify-send -u low -i "$NOTIFY_ICON" \
                "Updates available!" "$UPDATES packages need updating"
        fi
    fi

    # When updates are available, check every 1 min
    while (( UPDATES > 0 )); do
        if (( UPDATES == 1 )); then
            echo "$UPDATES"
        elif (( UPDATES > 1 )); then
            echo "$UPDATES"
        else
            echo "None"
        fi

        sleep 60
        get_total_updates
    done
    

    # When no updates are available, check every 30 min
    # to save those precious CPU cycles
    while (( UPDATES == 0 )); do
        echo "None"
        sleep 1800
        get_total_updates
    done
done
